# Generated by Django 2.2.3 on 2019-07-22 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('harmonize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='acousticness',
        ),
        migrations.RemoveField(
            model_name='track',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='track',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='track',
            name='instrumentalness',
        ),
        migrations.RemoveField(
            model_name='track',
            name='liveness',
        ),
        migrations.RemoveField(
            model_name='track',
            name='loudness',
        ),
        migrations.RemoveField(
            model_name='track',
            name='speechiness',
        ),
        migrations.RemoveField(
            model_name='track',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='track',
            name='valence',
        ),
        migrations.CreateModel(
            name='WeightedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmonize.Tag')),
            ],
        ),
    ]
