# Generated by Django 2.2.3 on 2019-07-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0004_auto_20190723_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='discogs_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='discogs_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartplaylist',
            name='discogs_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='discogs_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
