# Generated by Django 2.2.3 on 2019-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0005_auto_20190724_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightedtag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='weightedtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='album',
            name='discogs_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='discogs_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='discogs_id',
        ),
        migrations.AddField(
            model_name='artist',
            name='related_artists',
            field=models.ManyToManyField(related_name='_artist_related_artists_+', to='harmonize.Artist'),
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='harmonize.Genre'),
        ),
        migrations.DeleteModel(
            name='SmartPlaylist',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='WeightedTag',
        ),
    ]
