# Generated by Django 2.2.3 on 2019-07-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0006_auto_20190727_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spotify_uri', models.CharField(blank=True, max_length=255, unique=True)),
                ('n', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmonize.Artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
