# Generated by Django 2.2.3 on 2019-07-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0007_smartplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplaylist',
            name='excluded_albums',
            field=models.ManyToManyField(related_name='_smartplaylist_excluded_albums_+', to='harmonize.Album'),
        ),
        migrations.AddField(
            model_name='smartplaylist',
            name='included_albums',
            field=models.ManyToManyField(related_name='_smartplaylist_included_albums_+', to='harmonize.Album'),
        ),
    ]
