# Generated by Django 2.2.3 on 2019-07-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0008_auto_20190728_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='smartplaylist',
            name='excluded_artists',
            field=models.ManyToManyField(blank=True, related_name='_smartplaylist_excluded_artists_+', to='harmonize.Artist'),
        ),
        migrations.AlterField(
            model_name='smartplaylist',
            name='excluded_albums',
            field=models.ManyToManyField(blank=True, related_name='_smartplaylist_excluded_albums_+', to='harmonize.Album'),
        ),
        migrations.AlterField(
            model_name='smartplaylist',
            name='included_albums',
            field=models.ManyToManyField(blank=True, related_name='_smartplaylist_included_albums_+', to='harmonize.Album'),
        ),
    ]
