# Generated by Django 2.2.3 on 2020-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0009_auto_20190728_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='acousticness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='danceability',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='energy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='instrumentalness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='key',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='liveness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='loudness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='mode',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='speechiness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='valence',
            field=models.FloatField(null=True),
        ),
    ]
