# Generated by Django 2.2.3 on 2020-04-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0010_auto_20200418_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='compressed_tempo',
            field=models.FloatField(null=True),
        ),
    ]
