# Generated by Django 2.2.3 on 2020-04-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0011_auto_20200419_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
