# Generated by Django 2.2.3 on 2020-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0013_auto_20200510_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similartrack',
            name='distance',
            field=models.FloatField(),
        ),
    ]
