# Generated by Django 3.0.6 on 2020-05-16 17:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0016_smartplaylist_seed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartplaylist',
            old_name='filter',
            new_name='seed_filter',
        ),
        migrations.AddField(
            model_name='smartplaylist',
            name='result_filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartplaylist',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
