# Generated by Django 3.0.6 on 2020-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0017_auto_20200516_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplaylist',
            name='track_limit',
            field=models.IntegerField(default=75),
        ),
    ]
