# Generated by Django 3.0.6 on 2021-03-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0024_auto_20210327_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='tracks',
            field=models.ManyToManyField(to='harmonize.Track'),
        ),
        migrations.DeleteModel(
            name='SavedTrack',
        ),
    ]
