# Generated by Django 3.0.6 on 2021-03-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0025_auto_20210327_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='saved',
        ),
    ]
