# Generated by Django 3.2 on 2021-07-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0026_remove_track_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartplaylist',
            name='result_filter',
        ),
        migrations.AlterField(
            model_name='playlisthistory',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_history', to='harmonize.smartplaylist'),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, to='harmonize.Track'),
        ),
    ]
