# Generated by Django 3.2 on 2021-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0028_auto_20210723_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartplaylist',
            old_name='seed_filter',
            new_name='track_filter',
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='harmonize.Track'),
        ),
    ]
