# Generated by Django 3.2 on 2021-10-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmonize', '0030_auto_20211001_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmonize.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmonize.spotifyuser')),
            ],
        ),
    ]
